### ISSUE TITLE
add --verbose flag so I can watch pip-compile progress

### ISSUE THREAD

**Issue by graingert** [peterdemin/pip-compile-multi#153] opened 2019-08-08 11:15 UTC
https://github.com/jazzband/pip-tools/issues/521

**Comment by peterdemin** [comment] 2019-08-08 19:06
I've read the linked issue, and my understanding of the problem is that at times pip-tools runs extremely slow and it's hard to tell if it's making any progress (correct me if I'm wrong).
While having a progress bar might look nice, I feel like this feature will make code harder to maintain without any adding practical benefit.
I'm closing the issue, but feel free to reopen with a good argument.

**Comment by graingert** [comment] 2019-08-08 19:10
Even without the progress bar it's good to be able to see what package is taking a long time

**Comment by peterdemin** [comment] 2019-08-08 19:18
Yeah, must be feeling good, but how does this information help? I mean, there is no way to speed up any particular package. `pip-tools` will take as much time as it needs. And the slow package will be slow during installation too, so it's not an insight.

**Comment by graingert** [comment] 2019-10-07 15:07
@peterdemin I don't really care too much about the progress bar, just some sort of verbose output

sometimes I end up with pathological cases where it's sat retrying because I forgot to connect to the VPN

**Comment by peterdemin** [comment] 2019-10-07 15:28
I'll be happy to review the PR with this  feature. `-v/—verbose ` that streams live pip-tools progress.

**Comment by john-sandall** [comment] 2021-03-20 20:59
@graingert Stumbled across this whilst searching for exactly the same thing. I've sketched out a partial solution in #247, reckon it's got legs?

**Comment by john-sandall** [comment] 2021-05-10 15:39
Closed by #251?

**Comment by peterdemin** [comment] 2021-05-10 15:40
Yes, thanks!

**Closed by peterdemin** 2021-05-10 15:40 UTC
